default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: <%= ENV['DATABASE'] || 'usernames_declensions' %>

test:
  <<: *default
  database: <%= ENV['DATABASE'] || 'usernames_declensions_test' %>

production:
  <<: *default