default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_LOGIN'] %>
  password: <%= ENV['DB_PASS'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'usernames_declensions' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'usernames_declensions_test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>